import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div className="min-h-screen bg-[#06202A] text-gray-300">
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Nav />

      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => {
    if (res != null) {
      res.json();
    } else {
      return null;
    }
  });

  if (request != null) {
    return {
      props: {
        results: request.results,
      },
    };
  } else {
    return {
      props: {
        results: [{ id: 1, title: "test" }],
      },
    };
  }
}
